# Generated by Django 4.2.18 on 2025-02-07 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_question_answer_remove_question_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='reverse_question',
        ),
    ]
