# Generated by Django 4.2.18 on 2025-02-07 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_question_reverse_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='original_word',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='translated_word',
            new_name='question',
        ),
    ]
